### ISSUE TITLE
Fails if definition for expected type can't be found

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/BioschemasMarkupGenerator#9]
If it can't find a description for a Schema.org type it throws an error but works. HOWEVER, if it cannot find the BSc description it throws an error and fails without telling you. The yaml looks OK, but cannot be loaded.

**Comment by AlasdairGray** [comment]
Which type is missing? What yaml looks ok?

http://www.macs.hw.ac.uk/~ajg33

________________________________

**Comment by AlasdairGray** [comment]
Came across this issue today with DNA being an expected type for a property but there is no associated Bioschemas profile for it. I have fixed the code (b1c1c552f92d7a5959a56c621ea99e511d010e9c ) so that it will now allow the property to be included but requires an `@id` link to a resource that has the detail.
